name: caseforai-backend
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - python-multipart==0.0.6
    - python-dotenv==1.0.0
    - llama-index==0.9.48
    - llama-index-embeddings-gemini==0.1.6
    - llama-index-vector-stores-pinecone==0.1.3
    - llama-index-readers-file==0.1.4
    - pinecone-client==3.2.2
    - google-generativeai==0.3.2